### ISSUE TITLE
Unusally Long Org name

### ISSUE THREAD

**Issue by ch3ck** [WoCUG/user-group-website#1]
@ch3nkula Change the Organization's name to Wikimedia Cameroon. the Wikimedia Community User Group Cameroon can be the description.

**Comment by xSavitar** [comment]
Its a naming convention in the Org. Wikimedia Cameroon is the name of a Chapter and not a UG. So that is the constraint that I have.

**Comment by ghost** [comment]
The Org name has been changed. Thanks for the suggestion 👍
